AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dmc-sam-app

  Sample SAM Template for dmc-sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
# レコード追加
  DmcPostFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function inserts data into DynamoDB table'
    Properties:
      FunctionName: DmcPostFunction
      Handler: post.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DailyMoodsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
# レコード削除
  DmcDeleteFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function deletes data in DynamoDB table'
    Properties:
      FunctionName: DmcDelFunction
      Handler: delete.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: DELETE
# レコード取得
  DmcGetFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function gets data from DynamoDB table'
    Properties:
      FunctionName: DailyMoodsGetFunction
      Handler: get_dm.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DailyMoodsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /get-dm
            Method: POST
# レコード取得（期間指定）
  DmsGetFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function gets data from DynamoDB table'
    Properties:
      FunctionName: DmsGetFunction
      Handler: get_dms.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DailyMoodsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /get-dms
            Method: POST
# ActivityLabelsTable
# レコード取得
  ActivityLabelsGetFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function gets activity labels data from DynamoDB table'
    Properties:
      FunctionName: ActivityLabelsGetFunction
      Handler: get_labels.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref ActivityLabelsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /get-labels
            Method: POST
# ActivityLabelsTable
# レコード作成
  ActivityLabelsPostFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function inserts activity labels data from DynamoDB table'
    Properties:
      FunctionName: ActivityLabelsPostFunction
      Handler: post_labels.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref ActivityLabelsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /labels
            Method: POST
# ActivityLabelsTable
# レコード削除
  ActivityLabelsDeleteFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function deletes activity labels data in DynamoDB table'
    Properties:
      FunctionName: ActivityLabelsDelFunction
      Handler: delete_labels.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref ActivityLabelsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /labels
            Method: DELETE
# DynamoDB
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DmcData
# Templates Table
  DmcTemplatesTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "template_id"
          AttributeType: "S"
        - 
          AttributeName: "created_by"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "template_id"
          KeyType: "HASH"
      TableName: "DmcTemplates"
      BillingMode: "PAY_PER_REQUEST"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "created_by_index"
          KeySchema: 
            - 
              AttributeName: "created_by"
              KeyType: "HASH"
          Projection: 
            ProjectionType: ALL
# User Table
  UsersTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "user_id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "user_id"
          KeyType: "HASH"
      TableName: "Users"
      BillingMode: "PAY_PER_REQUEST"
# DailyMoods Table
  DailyMoodsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "user_id"
          AttributeType: "S"
        - 
          AttributeName: "date"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "user_id"
          KeyType: "HASH"
        - 
          AttributeName: "date"
          KeyType: "RANGE"
      TableName: "DailyMoods"
      BillingMode: "PAY_PER_REQUEST"
# ActivityLabels Table
  ActivityLabelsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "user_id"
          AttributeType: "S"
        - 
          AttributeName: "label_id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "user_id"
          KeyType: "HASH"
        - 
          AttributeName: "label_id"
          KeyType: "RANGE"
      TableName: "ActivityLabels"
      BillingMode: "PAY_PER_REQUEST"
Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'